### ISSUE TITLE
Python 3 traceback related to strings

### ISSUE THREAD

**Issue by andreasvc** [andreasvc/cplay#2]
```
Traceback (most recent call last):
  File "/usr/local/bin/cplay", line 1894, in main
    APP.run()
  File "/usr/local/bin/cplay", line 1559, in run
    self.control.handle_command()
  File "/usr/local/bin/cplay", line 1418, in handle_command
    argv = self.fd.readline().strip().split(" ", 1)
TypeError: Type str doesn't support the buffer API
```

**Comment by andreasvc** [comment]
Fixed by passing None to .split().
